### ISSUE TITLE
Error while installing the nosh 3

### ISSUE THREAD

**Issue by gautam071** [shihjay2/nosh3#4]
I am trying to install the nosh 3 projects locally, but I am facing some issues with the installation steps with [Easy Installation ](https://github.com/shihjay2/nosh3#easy-installation) as well as the [Detailed installation ](https://github.com/shihjay2/nosh3#detailed-installation) 

Sharing the screenshot of the error
<img width="1431" alt="Screenshot 2023-02-07 at 8 40 37 PM" src="https://user-images.githubusercontent.com/73119570/217284344-0b7f53c0-c22a-481c-a940-c2076287aef5.png">
<img width="1209" alt="Screenshot 2023-02-07 at 8 44 15 PM" src="https://user-images.githubusercontent.com/73119570/217284520-0c370bd8-7012-41ef-81dd-553ea9238b56.png">

**Comment by shihjay2** [comment]
Typo in readme.  Fixed in commit [3a861b0].(https://github.com/shihjay2/nosh3/commit/3a861b00de04f62d553e7625c3ff9e42352bd7c8)

**Comment by gautam071** [comment]
@shihjay2 I am still facing the same error with the updated code
![Screenshot 2023-02-09 at 4 54 49 PM](https://user-images.githubusercontent.com/73119570/217800092-b0999890-dac8-4cf0-a4c4-7c125a3a03f3.png)

**Comment by shihjay2** [comment]
Are you running the command inside a DigitalOcean droplet?  If not, you might need to confirm internet access or DNS server configurations.  You can try 
```
curl -O https://raw.githubusercontent.com/shihjay2/nosh3/main/do-install.sh
chmod +x do-install.sh
./do-install.sh
````
but make sure curl is installed (if it still doesn't work, then I can't explain why your server cannot reach the file without checking the queries I mentioned above).
